# Generated by Django 3.2.6 on 2021-09-03 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preguntas', '0005_merge_20210902_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación', verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, help_text='Fecha de modificación', verbose_name='modificado')),
                ('finalizado', models.BooleanField(default=False)),
                ('dificultad', models.CharField(choices=[('1', 'Fácil'), ('2', 'Media'), ('3', 'Difícil')], default='1', max_length=1)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('preguntas', models.ManyToManyField(related_name='Preguntas_del_Juego', to='preguntas.Pregunta')),
            ],
            options={
                'db_table': 'Juegos',
            },
        ),
    ]
