# Generated by Django 3.2.6 on 2021-08-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_remove_pregunta_datoobligatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
