# Generated by Django 3.2.6 on 2021-09-03 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0004_alter_pregunta_dificultad'),
        ('preguntas', '0004_auto_20210831_2356'),
    ]

    operations = [
    ]
